"""add file_url column to query table

Revision ID: 136eb98c8f01
Revises: e08c9085c726
Create Date: 2025-07-29 20:01:18.125779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136eb98c8f01'
down_revision: Union[str, Sequence[str], None] = 'e08c9085c726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('file_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query', 'file_url')
    # ### end Alembic commands ###
